[tool.ruff]
include = ["*.py", "*.pyi", "**/pyproject.toml"]
select = [
    "D",  # pydocstyle
    "F",  # Pyflakes
    "E",  # pycodestyle
    "W",  # pycodestyle
    "N",  # pep8-naming
    "I001",  # isort
    "ANN",  # flake8-annotations
    "BLE",  # flake8-blind-except
    "B",  # flake8-bugbear
    "A",  # flake8-builtins
    "COM",  # flake8-commas
    "DTZ",  # flake8-datetimez
    "EM",  # flake8-errmsg
    "ISC",  # flake8-implicit-str-concat
    "ICN",  # flake8-import-conventions
    "G",  # flake8-logging-format
    "T20",  # flake8-print
    "Q",  # flake8-quotes
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
    "TID",  # flake8-tidy-imports
    "ARG",  # flake8-unused-arguments
    "PTH",  # flake8-use-pathlib
    "TD",  # flake8-todos
    "FIX",  # flake8-fixme
    "ERA",  # eradicate
    "PL",  # Pylint
    "TRY",  # tryceratops
]

[tool.ruff.pydocstyle]
convention = "numpy"
